/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f5faf8",
        "surface-dim": "#d6dbd9",
        "surface-bright": "#f5faf8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f5f2",
        "surface-container": "#eaefed",
        "surface-container-high": "#e4e9e7",
        "surface-container-highest": "#dee4e1",
        "on-surface": "#171d1c",
        "on-surface-variant": "#3d4947",
        "inverse-surface": "#2c3130",
        "inverse-on-surface": "#edf2f0",
        outline: "#6d7a77",
        "outline-variant": "#bcc9c6",
        primary: "#00685f",
        "on-primary": "#ffffff",
        "primary-container": "#008378",
        "on-primary-container": "#f4fffc",
        "inverse-primary": "#6bd8cb",
        secondary: "#006c49",
        "on-secondary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "on-secondary-container": "#00714d",
        tertiary: "#825100",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a36700",
        "on-tertiary-container": "#fffbff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f5faf8",
        "on-background": "#171d1c",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        card: "0 4px 20px 0 rgba(0,0,0,0.04)",
        overlay: "0 10px 30px 0 rgba(0,0,0,0.08)",
      },
    },
  },
  plugins: [],
};
