"use client";

import { useEffect, useState, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import DashboardShell from "@/components/DashboardShell";
import RiskBadge from "@/components/RiskBadge";
import { screeningsApi, dogsApi, ScreeningResult, Dog } from "@/lib/api";

function ReportContent() {
  const params = useSearchParams();
  const id = params.get("id");
  const [screening, setScreening] = useState<ScreeningResult | null>(null);
  const [dog, setDog] = useState<Dog | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) {
      setLoading(false);
      return;
    }
    screeningsApi.get(id).then(async (s) => {
      setScreening(s);
      const d = await dogsApi.get(s.dog_id);
      setDog(d);
      setLoading(false);
    });
  }, [id]);

  if (!id) {
    return <div className="card text-center text-on-surface-variant">Select a screening from your history to view its report.</div>;
  }
  if (loading) return <p className="text-on-surface-variant">Loading report...</p>;
  if (!screening || !dog) return <p className="text-on-surface-variant">Report not found.</p>;

  return (
    <div className="card print:shadow-none">
      <div className="mb-6 flex items-center justify-between border-b border-outline-variant/40 pb-6">
        <div>
          <p className="text-sm text-on-surface-variant">VetGuard AI Screening Report</p>
          <h1 className="text-2xl font-semibold text-on-surface">{dog.name}</h1>
        </div>
        <button onClick={() => window.print()} className="btn-secondary print:hidden">
          Print / Save as PDF
        </button>
      </div>

      <div className="mb-6 grid grid-cols-2 gap-4 text-sm sm:grid-cols-4">
        <div>
          <p className="text-on-surface-variant">Breed</p>
          <p className="font-medium text-on-surface">{dog.breed}</p>
        </div>
        <div>
          <p className="text-on-surface-variant">Age</p>
          <p className="font-medium text-on-surface">{dog.age_months} months</p>
        </div>
        <div>
          <p className="text-on-surface-variant">Weight</p>
          <p className="font-medium text-on-surface">{dog.weight_kg} kg</p>
        </div>
        <div>
          <p className="text-on-surface-variant">Screened on</p>
          <p className="font-medium text-on-surface">{new Date(screening.created_at).toLocaleString()}</p>
        </div>
      </div>

      <div className="mb-6 flex items-center justify-between rounded-lg bg-surface-container-low p-5">
        <div>
          <p className="text-sm text-on-surface-variant">Predicted condition</p>
          <p className="text-2xl font-semibold text-on-surface">{screening.predicted_disease}</p>
          <p className="mt-1 text-sm text-on-surface-variant">{Math.round(screening.confidence * 100)}% model confidence · {screening.model_name}</p>
        </div>
        <RiskBadge level={screening.risk_level} />
      </div>

      <div className="mb-6">
        <p className="mb-2 text-sm font-semibold text-on-surface">Probability breakdown</p>
        <div className="space-y-2">
          {Object.entries(screening.probabilities)
            .sort((a, b) => b[1] - a[1])
            .map(([disease, prob]) => (
              <div key={disease} className="flex items-center gap-3">
                <span className="w-32 shrink-0 text-sm text-on-surface-variant">{disease}</span>
                <div className="h-2 flex-1 overflow-hidden rounded-full bg-surface-container">
                  <div className="h-full bg-primary" style={{ width: `${prob * 100}%` }} />
                </div>
                <span className="w-12 text-right text-sm text-on-surface-variant">{Math.round(prob * 100)}%</span>
              </div>
            ))}
        </div>
      </div>

      {screening.human_exposure_flag && (
        <div className="mb-6 rounded-lg border border-error bg-error-container/30 p-4">
          <p className="text-sm font-semibold text-on-error-container">Human exposure flagged</p>
          <p className="mt-1 text-sm text-on-error-container">{screening.human_exposure_message}</p>
        </div>
      )}

      <div className="mb-6 rounded-lg bg-secondary-container/20 p-4">
        <p className="text-sm font-semibold text-on-surface">Recommendation</p>
        <p className="mt-1 text-sm text-on-surface-variant">{screening.recommendation}</p>
      </div>

      <p className="border-t border-outline-variant/40 pt-4 text-xs text-on-surface-variant">
        This report is generated by an AI-based preliminary screening tool developed as part of an academic
        project. It is not a veterinary diagnosis and must not replace clinical examination or laboratory
        confirmation. Please consult a licensed veterinarian for definitive diagnosis and treatment.
      </p>
    </div>
  );
}

export default function ReportsPage() {
  return (
    <DashboardShell>
      <h1 className="mb-6 text-2xl font-semibold text-on-surface print:hidden">Reports</h1>
      <Suspense fallback={<p className="text-on-surface-variant">Loading...</p>}>
        <ReportContent />
      </Suspense>
    </DashboardShell>
  );
}
